import json
from pathlib import Path
import uuid
from typing import Any, Callable, Set
import pytesseract
from PIL import Image

# Function to extract text from an image file
def extract_text_from_image(image_path: str) -> str:
    try:
        img = Image.open(image_path)
        text = pytesseract.image_to_string(img)
        return text
    except Exception as e:
        return f"Error extracting text: {e}"

# Function to create a recipe file from grocery and menu images
def create_recipe_from_images(grocery_image_path: str, menu_image_path: str) -> str:
    script_dir = Path(__file__).parent
    recipe_id = str(uuid.uuid4()).replace('-', '')[:6]
    file_name = f"recipe-{recipe_id}.txt"
    file_path = script_dir / file_name

    # Extract text from images
    grocery_text = extract_text_from_image(grocery_image_path)
    menu_text = extract_text_from_image(menu_image_path)

    # Save extracted text for agent to use in recipe generation
    content = (
        f"Recipe ID: {recipe_id}\n"
        f"Grocery List (from image):\n{grocery_text}\n"
        f"Menu Items (from image):\n{menu_text}\n"
        f"\n---\n"
        f"(Recipe will be generated by the agent using GPT-4o)"
    )
    file_path.write_text(content)

    message_json = json.dumps({
        "message": f"Extracted grocery and menu text saved as {file_name}. The agent will generate the recipe.",
        "file": file_name
    })
    return message_json

# Define a set of callable functions
user_functions: Set[Callable[..., Any]] = {
    create_recipe_from_images
}


